spring:
  application:
    name: BookAPI-GraphQL

  graphql:
    graphiql:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.amoura.bookapi.service: DEBUG
